export const EMAIL_SENT_SUCCESS = 'EMAIL_SENT_SUCCESS';
export const EMAIL_SENT_FAIL = 'EMAIL_SENT_FAIL';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const UPDATE_USER = 'UPDATE_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const CLEAR_STATUS = 'CLEAR_STATUS';

export const GET_NOTES = 'GET_NOTES';
export const GET_NOTES_BY_ID = 'GET_NOTES_BY_ID';
export const ADD_NOTE = 'ADD_NOTE';
export const INIT_ADD_NOTE = 'INIT_ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_CURRENT = 'SET_CURRENT';
export const SEARCH_NOTES = 'SEARCH_NOTES';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const NOTE_ERROR = 'NOTE_ERROR';
export const CLEAR_NOTES = 'CLEAR_NOTES';
export const SET_FILTER = 'SET_FILTER';

export const SET_LOADING = 'SET_LOADING';

export const RESPONSE_SENT = 'RESPONSE_SENT';
export const RESPONSE_SENDING_FAILED = 'RESPONSE_SENDING_FAILED';
export const SET_OPEN = 'SET_OPEN';
export const SET_QUERY_LOADING = 'SET_QUERY_LOADING';

export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_OPS_FAILED = 'PROFILE_OPS_FAILED';
export const SET_PROFILE_OPEN = 'SET_PROFILE_OPEN';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';